package permutas.constants

object Labels extends Enumeration {
  val ADD_AS_PAYEE,
  BROADCAST_CONTRACT_CONFIRM,
  BROADCAST_TX_CONFIRM,
  CREATE_CHANNEL_CONFIRM,
  ENTER_SPEND_AMOUNT,
  HTLC_COUNTER_OFFER,
  HTLC_FILL,
  HTLC_REFUND,
  HTLC_SWEEP,
  INCOMING_TX,
  INCOMING_NTX,
  NEXT,
  OPEN_LINK,
  OUTGOING_TX,
  PREV,
  TX_HASH,
  TX_SET_MEMO,
  SWAP_FILL,
  VALUE_SENT_TO_ME,
  VALUE_SENT_FROM_ME,
  VIEW_CONTRACT = Value
}